package com.mabrouk.recall.core.model

/**
 * Opaque identifier for a [Note]. Generated by [com.mabrouk.recall.data.repository]
 * on create — callers do not mint IDs.
 */
data class NoteId(val value: String)
