package com.mabrouk.recall.core.designsystem.theme

import androidx.compose.ui.graphics.Color

// Recall brand scheme.
// Generated with Material Theme Builder from the teal seed #0F766E.
// This is the fallback / branded scheme; dynamic color (Material You)
// overrides it at runtime on Android 12+.

// Light
val primaryLight = Color(0xFF006A60)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF9EF2E4)
val onPrimaryContainerLight = Color(0xFF00201C)
val secondaryLight = Color(0xFF4A635E)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFCCE8E1)
val onSecondaryContainerLight = Color(0xFF06201B)
val tertiaryLight = Color(0xFF446279)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFCAE6FF)
val onTertiaryContainerLight = Color(0xFF001E30)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFAFDFA)
val onBackgroundLight = Color(0xFF191C1B)
val surfaceLight = Color(0xFFFAFDFA)
val onSurfaceLight = Color(0xFF191C1B)
val surfaceVariantLight = Color(0xFFDAE5E1)
val onSurfaceVariantLight = Color(0xFF3F4946)
val outlineLight = Color(0xFF6F7976)
val outlineVariantLight = Color(0xFFBEC9C5)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2D3130)
val inverseOnSurfaceLight = Color(0xFFEFF1EF)
val inversePrimaryLight = Color(0xFF82D5C8)

// Dark
val primaryDark = Color(0xFF82D5C8)
val onPrimaryDark = Color(0xFF003731)
val primaryContainerDark = Color(0xFF005048)
val onPrimaryContainerDark = Color(0xFF9EF2E4)
val secondaryDark = Color(0xFFB1CCC5)
val onSecondaryDark = Color(0xFF1C3530)
val secondaryContainerDark = Color(0xFF334B46)
val onSecondaryContainerDark = Color(0xFFCCE8E1)
val tertiaryDark = Color(0xFFACCBE5)
val onTertiaryDark = Color(0xFF123349)
val tertiaryContainerDark = Color(0xFF2B4A60)
val onTertiaryContainerDark = Color(0xFFCAE6FF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF191C1B)
val onBackgroundDark = Color(0xFFE0E3E1)
val surfaceDark = Color(0xFF191C1B)
val onSurfaceDark = Color(0xFFE0E3E1)
val surfaceVariantDark = Color(0xFF3F4946)
val onSurfaceVariantDark = Color(0xFFBEC9C5)
val outlineDark = Color(0xFF899390)
val outlineVariantDark = Color(0xFF3F4946)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE0E3E1)
val inverseOnSurfaceDark = Color(0xFF191C1B)
val inversePrimaryDark = Color(0xFF006A60)
